#format = "[](bg:#546e7a fg:#26C6DA)[ ](bg:#546e7a fg:#26C6DA)$directory($git_branch)\n$character"
#format = "[  ](bg:#8fbcbb fg:#3b4252)$directory($git_branch) $git_metrics\n$character"
#format = "[  ](bg:#8fbcbb fg:#3b4252)$directory($git_branch)\n$character"

format = "[  ](bg:#8fbcbb fg:#3b4252)$directory($git_branch) $docker_context\n$character"



[character]
success_symbol = "[➜](bold green)"
error_symbol   = "[➜](bold red)"

[battery]
disabled = true

[cmd_duration]
format = "[$duration]($style)"
style = 'bright-black'

[directory]
style = "#3b4252"
format = "[](bg:#3b4252 fg:#8fbcbb)[ $path ](bg:#3b4252 fg:#d8dee9)[](fg:$style)"


[git_branch]
style = "bg:cyan fg:black"
#format = "[ ](fg:cyan)[ $symbol $branch]($style)[ ](bg:cyan)[](fg:cyan)"
format = "[](bg:cyan fg:black)[ $symbol $branch]($style)[ ](bg:cyan)[](fg:cyan)"
symbol = ""

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"


[git_status]
# disabled = true
style = "bg:green fg:black"
stashed = " ${count}"
ahead = "ﲗ ${count}"
behind = "ﲔ ${count}"
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = "${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " 凜${count}"
staged = "  ${count}"
untracked = "  ${count}"
format = "([[](bg:#E0B25D fg:#464347)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[](fg:#E0B25D)]($style))"
#format = "[](bg:cyan fg:black)[ $symbol $branch]($style)[ ](bg:cyan)[](fg:cyan)"

[docker_context]
symbol = " "
format = "via [$symbol$context]($style) "
style = "blue bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []

[nodejs]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[lua]
disabled = true


